name: Kernel Build CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
       image: fedora:rawhide

    steps:
    - uses: actions/checkout@v2
    - name: Setup build environment
      run: |
        sudo dnf groupinstall "Development tools" -y
        sudo dnf install bison flex bc openssl-devel -y
        sudo dnf install 'dnf-command(config-manager)' -y
        sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo -y
        sudo dnf install gh -y
    - name: Set date
      id: get-date
      run: |
        ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
        echo "date=$(/bin/date -u '+%d%m%Y%I%M')" >> $GITHUB_ENV
    - name: Configure
      run: make wsl_defconfig
    - name: Build Kernel
      run: |
        export KBUILD_BUILD_USER="mvaisakh"
        export KBUILD_BUILD_HOST="statixos"
        make -j$(nproc --all)
        echo "kversion=string arch/x86_64/boot/bzImage | grep mvaisakh | grep gcc" >> $GITHUB_ENV
    - name: Create Release
      run: |
        gh release create ${{ env.date }} 'arch/x86_64/boot/bzImage#kernel' --notes "Version String: ${{ env.kversion }}" --generate-notes -t "Eva Kernel for WSL Release ${{ env.date }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}