name: Kernel Build CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
       image: fedora:rawhide

    steps:
    - name: Setup build environment
      run: |
        sudo dnf groupinstall "Development tools" -y
        sudo dnf install bison flex bc openssl-devel -y
        sudo dnf install 'dnf-command(config-manager)' -y
        sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo -y
        sudo dnf install gh -y
    - name: Set date
      id: get-date
      run: |
        ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
        echo "date=$(/bin/date -u '+%d%m%Y%I%M')" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Create release asset dir
      run: mkdir -p releases
    - name: Configure
      run: make wsl_defconfig
    - name: Build Kernel
      run: |
        git config --global --add safe.directory /__w/wsl-kernel/wsl-kernel
        export KBUILD_BUILD_USER="mvaisakh"
        export KBUILD_BUILD_HOST="statixos"
        make -j$(nproc --all)
        echo "kversion=$(strings arch/x86_64/boot/bzImage | grep mvaisakh | grep gcc)" >> $GITHUB_ENV
        cp arch/x86_64/boot/bzImage releases/bzImage
    - name: Checkout to RT
      run: |
        git fetch https://github.com/mvaisakh/wsl-kernel wsl-rt
        git checkout FETCH_HEAD
    - name: Clean
      run: make clean && make mrproper
    - name: Configure
      run: make wsl_defconfig
    - name: Build Kernel
      run: |
        git config --global --add safe.directory /__w/wsl-kernel/wsl-kernel
        export KBUILD_BUILD_USER="mvaisakh"
        export KBUILD_BUILD_HOST="statixos"
        make -j$(nproc --all)
        echo "kversion-rt=$(strings arch/x86_64/boot/bzImage | grep mvaisakh | grep gcc)" >> $GITHUB_ENV
        cp arch/x86_64/boot/bzImage releases/bzImage-rt
    - name: Create Release
      run: |
        gh release create ${{ env.date }} 'releases/bzImage#kernel' 'releases/bzImage-rt#kernel-rt' --notes "Version String: ${{ env.kversion }} \n Version String RT: ${{ env.kversion-rt }}" --generate-notes -t "Eva Kernel for WSL Release ${{ env.date }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

